### ISSUE TITLE
Sharders can not get up with error on loading LFB

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#2336]
In /testnet, some sharders could not get up after running for a while with chaos tests. They failed to load LFB locally because they detected missing nodes when validate the LFB state, which should not happen as sharders run as full node. Checked 2 sharders that couldn't get up, though they starting from different LFB rounds, the missing nodes were the same. We fixed it in a workaround way to sync missing nodes from remote, but we should know what caused the missing nodes.

**Comment by devyetii** [comment]
Stuck into this as well. Let me add the panic log for reference
```
sharder_1    | panic: load_lfb, could not rollback to LFB with full state, please clean DB and sync again
sharder_1    | 
sharder_1    | goroutine 1 [running]:
sharder_1    | go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0xc0005c61a0, {0x0, 0x0, 0xafa6a0})
sharder_1    |  /0chain/code/go/0chain.net/vendor/go.uber.org/zap/zapcore/entry.go:198 +0x9b
sharder_1    | go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0005c61a0, {0xc0005cdc00, 0x2, 0x2})
sharder_1    |  /0chain/code/go/0chain.net/vendor/go.uber.org/zap/zapcore/entry.go:264 +0x61c
sharder_1    | go.uber.org/zap.(*Logger).Panic(0xc00027d0a0, {0x1bbfbeb, 0x53}, {0xc0005cdc00, 0x2, 0x2})
sharder_1    |  /0chain/code/go/0chain.net/vendor/go.uber.org/zap/logger.go:258 +0x6c
sharder_1    | 0chain.net/sharder.(*Chain).walkDownLookingForLFB(0x2414840, 0xc000bb0848, 0xc0002e4360)
sharder_1    |  /0chain/code/go/0chain.net/sharder/chain.go:338 +0x7f6
sharder_1    | 0chain.net/sharder.(*Chain).iterateRoundsLookingForLFB(0x2414840, {0x1ccb800, 0xc00008c840})
sharder_1    |  /0chain/code/go/0chain.net/sharder/chain.go:439 +0x2e5
sharder_1    | 0chain.net/sharder.(*Chain).LoadLatestBlocksFromStore(0x2414840, {0x1ccb800, 0xc00008c840})
sharder_1    |  /0chain/code/go/0chain.net/sharder/chain.go:478 +0x65
sharder_1    | main.main()
sharder_1    |  /0chain/code/go/0chain.net/sharder/sharder/sharder.go:251 +0x2911
```
