### ISSUE TITLE
Remove panic from  getFileWithoutExtension

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#297]
FSBlockStore.getFileWithoutExtension panics if the hash size is lsee than 9
```go
for i := 0; i &lt; 3; i++ {	
   file.WriteString(string(os.PathSeparator))		
   file.WriteString(hash[3*i : 3*i+3]) // FIXME panics if hash size < 9
}
```
So the fix me needs to be fixed.

This panic turned up in production
```
panic: runtime error: slice bounds out of range [:3] with length 0
goroutine 24910 [running]:
0chain.net/sharder/blockstore.(*FSBlockStore).getFileWithoutExtension(0xc00058a6f0, 0x0, 0x0, 0x307b1, 0x0, 0x0)
	/0chain/go/0chain.net/sharder/blockstore/fs_store.go:60 +0x2e4
0chain.net/sharder/blockstore.(*FSBlockStore).getFileName(0xc00058a6f0, 0x0, 0x0, 0x307b1, 0x0, 0x0)
	/0chain/go/0chain.net/sharder/blockstore/fs_store.go:70 +0x55
0chain.net/sharder/blockstore.(*FSBlockStore).UploadToCloud(0xc00058a6f0, 0x0, 0x0, 0x307b1, 0x0, 0x0)
	/0chain/go/0chain.net/sharder/blockstore/fs_store.go:220 +0x75
0chain.net/sharder.(*Chain).moveBlockToCloud(0x18b9c60, 0x12d4dc0, 0xc00008c4c0, 0x307b1, 0x0, 0x0, 0x12d9fc0, 0xc00058a6f0, 0xc000c0de60)
	/0chain/go/0chain.net/sharder/worker.go:238 +0x75
created by 0chain.net/sharder.(*Chain).MinioWorker
	/0chain/go/0chain.net/sharder/worker.go:225 +0x806
```

The real problem that caused this error is somewhere else, but nevertheless, we should find a more controlled way of handling an empty hash.

**Comment by rrrooommmaaa** [comment]
yep, this crashed the sharder on Jun 19 again

**Comment by Dmdv** [comment]
@Sriep Fixed in #602

**Comment by Dmdv** [comment]
https://0chain.github.io/system_test/master/956ef796578f8202a4a9265302491898394d633a/index.html

**Comment by Dmdv** [comment]
Fixed in #602
