### ISSUE TITLE
Sharder non-stop crashing

### ISSUE THREAD

**Issue by moldis** [0chain/0chain#479]
Giving the log below:

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb5d506]
goroutine 16 [running]:
0chain.net/chaincore/node.(*Pool).RequestEntity(0xc00092c820, 0x1205a30, 0xc0004e86c0, 0x0, 0xc0005a40f8, 0xc000556140, 0x0)
	/0chain.net/chaincore/node/n2n_request.go:40 +0x46
0chain.net/chaincore/chain.(*Chain).RequestEntityFromMinersOnMB(0xc000548a00, 0x1205a30, 0xc0004e86c0, 0xc0006b2900, 0x0, 0xc0005a40f8, 0xc000556140)
	/0chain.net/chaincore/chain/block_fetcher.go:488 +0x6b
0chain.net/chaincore/chain.(*Chain).getBlockStateChange(0xc000548a00, 0xc0001c8380, 0x0, 0x0, 0x0)
	/0chain.net/chaincore/chain/state_sync.go:338 +0x2ff
0chain.net/chaincore/chain.(*Chain).GetBlockStateChange(0xc000548a00, 0xc0001c8380, 0x0, 0x0)
	/0chain.net/chaincore/chain/state_sync.go:26 +0x5b
0chain.net/chaincore/chain.(*Chain).InitBlockState.func1(0xc00054e480, 0xc000548a00, 0xc0001c8380, 0xc00054e4e0)
	/0chain.net/chaincore/chain/entity.go:1267 +0x88
created by 0chain.net/chaincore/chain.(*Chain).InitBlockState
	/0chain.net/chaincore/chain/entity.go:1265 +0x5a5`

**Comment by guruhubb** [comment]
This has been fixed by recent push from Peter - https://github.com/0chain/0chain/commit/89039275c2332ce64db2dec8c21f45e650fe7770. Is this still happening?

**Comment by Sriep** [comment]
After two months assume this panic is fixed in https://github.com/0chain/0chain/pull/458.
