### ISSUE TITLE
[WIP] Persistencestore unit test error

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#62]
```
panic: nil [recovered]
    panic: test executed panic(nil) or runtime.Goexit
goroutine 12 [running]:
testing.tRunner.func1(0xc0000fe900)
    /usr/local/go/src/testing/testing.go:830 +0x392
panic(0x0, 0x0)
    /usr/local/go/src/runtime/panic.go:522 +0x1b5
0chain.net/core/persistencestore.InitSession()
    /0chain/go/0chain.net/core/persistencestore/connection.go:42 +0xcb
0chain.net/core/persistencestore.GetConnection(...)
    /0chain/go/0chain.net/core/persistencestore/connection.go:87
0chain.net/core/persistencestore.WithConnection(0xc71300, 0xc000024070, 0x41471dc, 0x41471dc00d89668)
    /0chain/go/0chain.net/core/persistencestore/connection.go:97 +0x97
0chain.net/core/persistencestore.WithEntityConnection(...)
    /0chain/go/0chain.net/core/persistencestore/connection.go:110
0chain.net/core/persistencestore.TestInsert(0xc0000fe900)
    /0chain/go/0chain.net/core/persistencestore/persistencestore_test.go:27 +0xe6
testing.tRunner(0xc0000fe900, 0xba8ad8)
    /usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
    /usr/local/go/src/testing/testing.go:916 +0x35a
FAIL    0chain.net/core/persistencestore    0.030s
```

**Comment by peterlimg** [comment]
We see this error because the test code tries to connect to a real cassandra instance, which does not exist at all for unit tests. So we have to mock the cassandra instances. 

Unfortunately, the gocql client package we are using does not use interfaces to communicate with cassandra, see details here https://github.com/gocql/gocql/issues/415#issuecomment-277530829. Hence, we will have to create interfaces and implement mockers by ourselves.
