### ISSUE TITLE
Test issue with redis

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#67]
Issues with Redis (couldn't connect during unit tests run)

```
--- FAIL: TestEntityWriteRead (0.00s)
panic: dial tcp 127.0.0.1:6379: connect: connection refused [recovered]
	panic: dial tcp 127.0.0.1:6379: connect: connection refused
goroutine 26 [running]:
testing.tRunner.func1(0xc000110700)
	/usr/local/go/src/testing/testing.go:830 +0x392
panic(0x97b4a0, 0xc000062010)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
0chain.net/core/memorystore.NewPool.func1(0xc00012b99c, 0x3, 0x3, 0x0)
	/0chain/go/0chain.net/core/memorystore/connection.go:43 +0xd3
github.com/gomodule/redigo/redis.(*Pool).get(0xc00012b960, 0x0, 0x0, 0x73bc8f, 0xc0000bc6e0, 0xc00010e0c0)
	/go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/pool.go:331 +0x43b
github.com/gomodule/redigo/redis.(*Pool).Get(0xc00012b960, 0xa3f224, 0x26)
	/go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/pool.go:179 +0x37
0chain.net/core/memorystore.GetConnection(0xc000132bd0)
	/0chain/go/0chain.net/core/memorystore/connection.go:159 +0x37c
0chain.net/core/memorystore.WithConnection(0xaef5e0, 0xc0001ee0c0, 0xc000132ae0, 0x0)
	/0chain/go/0chain.net/core/memorystore/connection.go:218 +0x149
0chain.net/core/memorystore.WithEntityConnection(0xaef5e0, 0xc0001ee0c0, 0xaf0420, 0xe533c0, 0xc00004bf18, 0x1)
	/0chain/go/0chain.net/core/memorystore/connection.go:261 +0xc50
0chain.net/core/memorystore.TestEntityWriteRead(0xc000110700)
	/0chain/go/0chain.net/core/memorystore/entity_test.go:76 +0x172
testing.tRunner(0xc000110700, 0xa4cfe8)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a
FAIL	0chain.net/core/memorystore	0.006s
```

**Comment by kirillt** [comment]
Also here:
```
time : 1612532288301
Testing at 2021-02-05 13:38:08.301476684 +0000 UTC m=+0.003196946
panic: dial tcp 127.0.0.1:6379: connect: connection refused

goroutine 29 [running]:
0chain.net/core/memorystore.NewPool.func1(0xc00012999c, 0x2000, 0x8, 0x7efdea093908)
    /0chain/go/0chain.net/core/memorystore/connection.go:43 +0xd3
github.com/gomodule/redigo/redis.(*Pool).get(0xc000129960, 0x0, 0x0, 0x740564, 0xc0000a8ae0, 0xff)
    /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/pool.go:331 +0x43b
github.com/gomodule/redigo/redis.(*Pool).Get(0xc000129960, 0xa638e9, 0x26)
    /go/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis/pool.go:179 +0x37
0chain.net/core/memorystore.GetConnection(0xc00040a960)
    /0chain/go/0chain.net/core/memorystore/connection.go:159 +0x37c
0chain.net/core/memorystore.WithConnection(0xb16e00, 0xc00013c1c0, 0xc000132330, 0x0)
    /0chain/go/0chain.net/core/memorystore/connection.go:218 +0x149
0chain.net/core/memorystore.WithEntityConnection(0xb16e00, 0xc00013c1c0, 0xb17cc0, 0xc0000d4910, 0x0, 0x0)
    /0chain/go/0chain.net/core/memorystore/connection.go:261 +0xc50
0chain.net/core/memorystore.(*MemoryDBChunkProcessor).Process(0xc00031d8e0, 0xb16e00, 0xc00013c1c0, 0xb16dc0, 0xc0003fc600)
    /0chain/go/0chain.net/core/memorystore/worker.go:85 +0x91
0chain.net/core/memorystore.(*MemoryDBChunkProcessor).Run(0xc00031d8e0, 0xb16e00, 0xc00013c1c0)
    /0chain/go/0chain.net/core/memorystore/worker.go:101 +0x70
created by 0chain.net/core/datastore.SetupChunkWorkers
    /0chain/go/0chain.net/core/datastore/worker.go:13 +0xe0
FAIL    0chain.net/chaincore/client 0.026s
```

**Comment by Sriep** [comment]
Moved to issue https://github.com/0chain/0chain/issues/130
